import re
import rocototop

def test_version_semver():
    # Regular expression for Semantic Versioning (SemVer)
    # This pattern matches versions like 0.1.2, 1.2.3-alpha.1, 2.0.0+build.184
    # and also the dev versions generated by setuptools-scm
    semver_pattern = r"^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"

    version = rocototop.__version__
    # setuptools-scm might use .dev instead of -dev for PEP 440 compatibility
    # PEP 440 is slightly different from pure SemVer but often used in Python
    # Let's check if it roughly follows the pattern

    # Standard PEP 440 version (which rocototop seems to use)
    pep440_pattern = r"^(\d+)\.(\d+)\.(\d+)(?:\.dev\d+)?(?:\+g[a-f0-9]+(?:\.d\d+)?)?$"

    assert re.match(pep440_pattern, version), f"Version {version} does not match PEP 440 / SemVer pattern"

def test_version_tuple():
    assert hasattr(rocototop, "version_tuple")
    assert isinstance(rocototop.version_tuple, tuple)
    assert len(rocototop.version_tuple) >= 3
    assert isinstance(rocototop.version_tuple[0], int)
    assert isinstance(rocototop.version_tuple[1], int)
    assert isinstance(rocototop.version_tuple[2], int)
